'use client'

import { Sparkles, Cpu } from 'lucide-react'
import { cn } from '@/lib/utils'

export function EngineBadge({
  engine,
  className,
}: {
  engine?: 'chutes' | 'zai' | string | null
  className?: string
}) {
  const isChutes = engine === 'chutes'
  return (
    <span
      className={cn(
        'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-medium',
        isChutes
          ? 'border-primary/30 bg-primary/10 text-primary'
          : 'border-accent-foreground/15 bg-accent text-accent-foreground',
        className
      )}
      title={isChutes ? 'Generated by Chutes LLM' : 'Generated by fallback engine'}
    >
      {isChutes ? <Sparkles className="size-3" /> : <Cpu className="size-3" />}
      {isChutes ? 'Chutes LLM' : 'AI Engine'}
    </span>
  )
}

export function PoweredByChutes({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        'inline-flex items-center gap-1.5 text-[11px] font-medium text-muted-foreground',
        className
      )}
    >
      <Sparkles className="size-3 text-primary" />
      Powered by Chutes LLM
    </span>
  )
}
